/**
 * Customer Feedback Kiosk - Google Apps Script backend
 *
 * Attach this script to the Google Sheet that should receive feedback.
 *
 * Expected POST fields:
 *   rating: 1, 2, or 3
 *   comment: optional text
 *   postcode: 4 digits
 *
 * The timestamp is generated by Google Apps Script.
 */

const SHEET_NAME = "Feedback";
const HEADERS = ["Timestamp", "Rating", "Comment", "Postcode"];

function doGet() {
  return ContentService
    .createTextOutput("Customer Feedback endpoint is running.")
    .setMimeType(ContentService.MimeType.TEXT);
}

function doPost(e) {
  try {
    const params = (e && e.parameter) ? e.parameter : {};

    const rating = String(params.rating || "").trim();
    const comment = String(params.comment || "").trim();
    const postcode = String(params.postcode || "").trim();

    // Validate server-side as well as in the kiosk.
    if (!["1", "2", "3"].includes(rating)) {
      return response_("Invalid rating.");
    }

    if (!/^\d{4}$/.test(postcode)) {
      return response_("Invalid postcode.");
    }

    const sheet = getFeedbackSheet_();

    // Store postcode as text so values such as 0123 retain their leading zero.
    sheet.appendRow([
      new Date(),
      Number(rating),
      comment,
      "'" + postcode
    ]);

    return response_("OK");
  } catch (error) {
    console.error(error);
    return response_("Server error.");
  }
}

function getFeedbackSheet_() {
  const spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = spreadsheet.getSheetByName(SHEET_NAME);

  if (!sheet) {
    sheet = spreadsheet.insertSheet(SHEET_NAME);
  }

  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, HEADERS.length).setValues([HEADERS]);
    sheet.setFrozenRows(1);
    sheet.getRange("A:A").setNumberFormat("dd/MM/yyyy HH:mm:ss");
  }

  return sheet;
}

function response_(message) {
  return ContentService
    .createTextOutput(message)
    .setMimeType(ContentService.MimeType.TEXT);
}
